[server]
headless = true
address = "127.0.0.1"
enableCORS = false
enableXsrfProtection = true
runOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "127.0.0.1"

[runner]
fastReruns = true

[client]
toolbarMode = "minimal"
